const DEFAULT_DRAWER_WIDTH = 240
const MIN_DRAWER_WIDTH = 64
const MAX_DRAWER_WIDTH = 416

export { DEFAULT_DRAWER_WIDTH, MIN_DRAWER_WIDTH, MAX_DRAWER_WIDTH }

export const DEFAULT_PAPER_ELEVATION = 2
